export const SET_FAVORITES = "SET_FAVORITES";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

export const SET_DOWNLOADS = "SET_DOWNLOADS";
export const ADD_DOWNLOAD = "ADD_DOWNLOAD";
export const REMOVE_DOWNLOAD = "REMOVE_DOWNLOAD";
export const UPDATE_DOWNLOAD = "UPDATE_DOWNLOAD";
